### ISSUE TITLE
upgrade build chain tool

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/idle-js#13]
We currently use webpack 1.0 and gulp.
We might want to use something like : 

- https://www.npmjs.com/package/microbundle
- https://github.com/hodgef/js-library-boilerplate (without the react part)

**Comment by nevf** [comment]
Or loose Webpack altogether and let us use Parcel.js or whatever loader we want. And why is babel and core-js needed, bloating the code size considerably.

**Comment by gabrielstuff** [comment]
@nevf morning ! use what ever you want. It's mostly ES6 now and you still have umd support.
