### ISSUE TITLE
💎- add ability to change the timeout dynamically

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/idle-js#19]
We would have something like:

`idle.set({timeout:3000})`

**Comment by gabrielstuff** [comment]
What do you think of this @himdel ?

**Comment by himdel** [comment]
Sounds reasonable :)

If we just rewrite settings, the change won't apply until `stop() & start()` gets called or until the `idlenessEventsHandler` fires.

Not sure that's bad, but sounds like it could be surprising in some cases.

If OTOH we call `resetTimeout` in `set`, as the code stands it will trigger `onActive` unless already active.

Heh, but that also means that calling `stop()` alredy fires `onActive` unless active, we should probably move that logic around a bit.

And once that's done, I guess we need to decide whether `set` automatically applies all the settings (and thus calls stop and start, and resets idleness state), or whether to document that:
* setting `idle`, `keepTracking`,  `recurIdleCall` applies on activity (or start),
* setting `on*` applies immediately, 
* setting `events` applies on start,
* setting `startAtIdle` applies on start or reset

**Comment by gabrielstuff** [comment]
Wow ! Thanks, looks great. Testing tonight.
