### ISSUE TITLE
stop function to pause idle.js in certain occasion

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/idle-js#2]

**Comment by legauntt** [comment]
👍 

Note that you can do:
```
var event = new CustomEvent("idle:stop", {});
window.dispatchEvent(event);
```

**Comment by gabrielstuff** [comment]
Nice found. Indeed we already have it here. https://github.com/soixantecircuits/idle-js/blob/ccd0d8ca3673a41efd9a69e60d0526cf84ec4ce5/src/Idle.js#L58 So we can just add a function : 

```
stop () {
  var event = new CustomEvent("idle:stop", {});
  window.dispatchEvent(event);
}
```

**Comment by legauntt** [comment]
Yep, but unfortunately that's broken. This PR fixes it: https://github.com/soixantecircuits/idle-js/pull/5

**Comment by gabrielstuff** [comment]
@himdel we have an issue with removing the eventlistener. I did not have time to fix it. Currently the examples does not pass. If you have time to check it. If not I will work on it later today.

**Comment by himdel** [comment]
@gabrielstuff Looking..

So far, looks like one of the issues is that `example/vanilla/index.html` is referencing `../dist` instead if `../../dist`...

And second issue.. somehow, the global object changed the name from `idleJs` to `IdleJs`.
(apparently in a77eeced)

With those changes (#14), the vanilla example works,
and the webpack one fails on missing `_idle`, still looking :).

**Comment by himdel** [comment]
`idle.stop()` fails with 

```
Idle.js:12 Uncaught ReferenceError: __idle is not defined
    at Idle.js:12
    at Array.forEach (<anonymous>)
    at bulkRemoveEventListener (Idle.js:11)
    at IdleJs.stop (Idle.js:91)
    at <anonymous>:1:6
```

even in the vanilla example, so the problem is in how we build `dist/`, not in the webpack example itself.

**Comment by himdel** [comment]
Oh! It's in the source .. comes from f7db055b, the `__idle` function is really not defined in the other function, as functions defined inside another function are local to the scope of the parent function only.

(Also, it can't work because the function gets created separately for each event type, so the reference won't be the same:

```
> a = [1,2,3].map((i) => function() {})
[ [Function], [Function], [Function] ]
> a[0] === a[1]
false

> f = function() {}
[Function: f]
> f === f
true
```
)

**Comment by himdel** [comment]
Fixed in https://github.com/soixantecircuits/idle-js/pull/17 :)

(And made a bunch more small PRs for things I noticed.)

**Comment by gabrielstuff** [comment]
thank @himdel, now we have 1.1.2 https://github.com/soixantecircuits/idle-js/releases/tag/v1.1.2 which include all of your contribution.

**Comment by gabrielstuff** [comment]
You can check out https://github.com/soixantecircuits/idle-vue/issues which depends on. For sure, you just gave a new breath to the project.

Thanks a lot!

**Comment by himdel** [comment]
Thanks @gabrielstuff , happy to hear that :). And thanks for making it easy :).

As for idle-vue, looks like most issues are either resolved now, or vue specific, or resolved except for the vue specific bits :),
so, I'm not sure I'll be able to help there much, Vue is the (only? :)) framework our app is currently not using :).
