### ISSUE TITLE
Add .babelrc to npmignore

### ISSUE THREAD

**Issue by choucalate** [soixantecircuits/idle-js#20]
Hi! Just had a couple of requests for this package 
1) Could we possibly add .babelrc to the npmignore? 
We're having some problems in jest because it is trying to use the devDependencies of @babel/preset-env and transform-object-assign, which is already generated in the dist/Idle.js 

2) Also, can we change the package.json's main to dist/Idle.min.js? 

Thank you!

**Comment by gabrielstuff** [comment]
hello @choucalate,

thanks for your feedback.

1. Yes, we can even use the `file` key to only ship the necessary files instead of blacklist with `.npmignore`

2. Why would you have a dist/Idle.min.js ? we only serve a minified version.

**Comment by choucalate** [comment]
Hey @gabrielstuff, thanks for your response
1. Yah a whitelist would definitely work
2. regarding the dist/Idle.min.js, sorry I think I was just looking at an older version where there was Idle.js and Idle.min.js, forget that comment 

Please let me know if you'd like me to submit a pr for #1, or if you're already working on it.  Thank you!

**Comment by gabrielstuff** [comment]
yes please PR it, I'm not planing on working on it today.

**Comment by choucalate** [comment]
Sounds good, just created a pr for it.
Thanks @gabrielstuff

**Comment by gabrielstuff** [comment]
Thanks @choucalate
