### ISSUE TITLE
onActive fires with idle.idle == true

### ISSUE THREAD

**Issue by himdel** [soixantecircuits/idle-js#6]
Looks like this is an oversight, all the other event handlers fire with their state already set right:

`onIdle`:
```js
      this.idle = true
      this.settings.onIdle.call()
```

`onShow`:
```js
            this.visible = true
            this.settings.onShow.call()
```

`onHide`:
```js
            this.visible = false
            this.settings.onHide.call()
```

**but** `onActive`:

```js
      settings.onActive.call()
      this.idle = false
```

So, when the `onActive` handler fires, `this.idle` is still set to true.

That makes it impossible to wait for visible & non-idle:

```js
  idle = new idleJs({
    idle: 60000, // idle after a minute
    onActive: maybePing,
    onShow: maybePing,
  });
  idle.start();

function maybePing() {
  if (! idle.visible)
    return;

  if (idle.idle)
    return;

  // never happens
}
```

**Comment by himdel** [comment]
(obviously wrapping the `onActive` handler in a `setTimeout` works as a workaround, but still :))

**Comment by gabrielstuff** [comment]
Hello @himdel, idle-js deserve a bit of love and I'll happy to merge your PR.

**Comment by himdel** [comment]
OK, I can definitely do a PR :).

Do you agree this was just an oversight, or do you remember any reason why this would be so intentionally? (I don't want to break anybody else :).)

**Comment by himdel** [comment]
@gabrielstuff A PR should be ready for all the issues now :)

Can you please take a look and release if everything works? :)
